#!/bin/bash
APP='docker-conf'

FLANNEL_SUBNET='/etc/flannel-subnet'

. /etc/flannel-subnet

FLANNEL_SUBNET=${FLANNEL_SUBNET:?'$FLANNEL_SUBNET is not set'}
FLANNEL_MTU=${FLANNEL_MTU:?'$FLANNEL_MTU is not set'}

echo "${APP}: Setting additional docker args - --bip=${FLANNEL_SUBNET}, --mtu=${FLANNEL_MTU}"
ros config set docker.extra_args "[--bip=${FLANNEL_SUBNET}, --mtu=${FLANNEL_MTU}]"
