#!/bin/bash +x
APP='nginx-proxy'

NGINX_PROXY_PASS=${NGINX_PROXY_PASS:?'$NGINX_PROXY_PASS url is not set'}
NGINX_SERVER_NAME=${NGINX_SERVER_NAME:?'$NGINX_SERVER_NAME is not set'}
OAUTH_PROXY_PASS=${OAUTH_PROXY_PASS:?'$OAUTH_PROXY_PASS url is not set'}

sed -i "s@{{ NGINX_PROXY_PASS }}@${NGINX_PROXY_PASS}@g;s@{{ NGINX_SERVER_NAME }}@${NGINX_SERVER_NAME}@g;s@{{ OAUTH_PROXY_PASS }}@${OAUTH_PROXY_PASS}@g"  /etc/nginx/proxy.conf

nginx "$@"
