#!/bin/bash
APP='kubelet-conf'

K8S_CLUSTER_ID=${K8S_CLUSTER_ID:?'$K8S_CLUSTER_ID is not set'}
K8S_MASTER=${K8S_MASTER:?'$K8S_MASTER is not set'}
K8S_S3_BUCKET=${K8S_S3_BUCKET:?'$K8S_S3_BUCKET is not set'}

MANIFESTS_PATH='/etc/kubernetes/manifests'
PODMASTER_MANIFESTS_PATH='/etc/kubernetes/podmaster'

CERTIFICATES="ca.pem client.pem client-key.pem api.pem api-key.pem"

K8S_PATH='/srv/kubernetes'

mkdir $MANIFESTS_PATH
for i in $(ls '/manifests'); do
  echo "${APP}: Creating manifest ${MANIFESTS_PATH}/${i}"
  sed "s/{{ K8S_CLUSTER_ID }}/${K8S_CLUSTER_ID}/g;s/{{ K8S_MASTER }}/${K8S_MASTER}/g" "/manifests/${i}" > "${MANIFESTS_PATH}/${i}"
done

mkdir $PODMASTER_MANIFESTS_PATH
for i in $(ls '/podmaster-manifests'); do
  echo "${APP}: Creating manifest ${PODMASTER_MANIFESTS_PATH}/${i}"
  sed "s/{{ K8S_CLUSTER_ID }}/${K8S_CLUSTER_ID}/g;s/{{ K8S_MASTER }}/${K8S_MASTER}/g" "/podmaster-manifests/${i}" > "${PODMASTER_MANIFESTS_PATH}/${i}"
done

# Get certificates
echo "${APP}: Downloading certificates"
for i in $CERTIFICATES; do
  echo "${APP}: ${i}"
  [[ -f "${K8S_PATH}/$i" ]] | aws s3api get-object --bucket "${K8S_S3_BUCKET}" --key "${i}" "${K8S_PATH}/${i}"
  [[ ! -f "${K8S_PATH}/$i" ]] && echo "${APP}: Error - failed to download ${i} certificate" && exit 1
done

# Touch log files, so they exists
touch /var/log/kube-apiserver.log
touch /var/log/kube-scheduler.log
touch /var/log/kube-controller-manager.log

# Auth file
touch /srv/kubernetes/known_tokens.csv
